lang: zh-CN

lobby: world

worlds-config:
  spectator-spawn-location: "0.5,65.0,0.5" # 旁观者的出生点
  spawn-locations:
    - "0,65,-19" # x,y,z 多出的部分会被自动截去
    - "-10,65,-17"
    - "-17,65,-10"
    - "-19,65,0"
    - "-17,65,10"
    - "-10,65,17"
    - "0,65,19"
    - "10,65,17"
    - "17,65,10"
    - "19,65,0"
    - "17,65,-10"
    - "10,65,-17"

  least-player: 2

  time-map: # 人数: 达到该人数后将倒计时缩短至
    2: 60 # 同时意味着最少人数(无论列表是否有序，程序会找到最小的人数)
    6: 30
    12: 15

  alive-award: 10
  kill-award: 60
  time-per-round: 60 # 给予物品之间的时间间隔，单位 tick
